SELECT * FROM GUESTBOOK_MESSAGE

CREATE SEQUENCE MY_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TABLE GUESTBOOK_MESSAGE (
	MESSAGE_ID NUMBER DEFAULT MY_SEQUENCE.NEXTVAL PRIMARY KEY, 
	GUEST_NAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(10) NOT NULL,
	MESSAGE VARCHAR2(150) NOT NULL
)