CREATE TABLE GUESTBOOK_MESSAGE (
	MESSAGE_ID INT not null AUTO_INCREMENT PRIMARY KEY, 
	GUEST_NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	MESSAGE TEXT NOT NULL
) engine=INNODB default CHARACTER set = UTF8